site_name: Beam Model Docs
theme:
  name: material
nav:
  - Home: index.md
  - Solvers: 
    - Utilities: utilities.md
    - Numerical Methods Logic: numericalmethods.md
    - Interpolation: interpolation.md
    - Mesh: mesh.md
    - Miscellaneous: misc.md
    - Boundary: boundary.md
    - FEM Solver: FEMSolver.md
plugins:
  - mkdocstrings: # This replaces "autodoc" to read your Python code
      handlers:
        python:
          paths: [.]