site_name: Beam Model Docs
theme:
  name: material
nav:
  - Home: index.md
  - Solvers: functions.md
    - Utilities: functions.md#utilities-section
    - Numerical Methods Logic: functions.md#math-section
    - Interpolation: functions.md#interpolation-section
    - Mesh: functions.md#mesh-section
    - Miscellaneous: functions.md#misc-section
plugins:
  - mkdocstrings: # This replaces "autodoc" to read your Python code
      handlers:
        python:
          paths: [.]