site_name: Beam Model Docs
theme:
  name: material
nav:
  - Home: index.md
  - Functions: functions.md
plugins:
  - mkdocstrings: # This replaces "autodoc" to read your Python code
      handlers:
        python:
          paths: [.]