name: Generate Documentation
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip install sphinx sphinx-rtd-theme numpy matplotlib scipy itertools time  # Add whatever you use here
      - name: Build HTML
        run: |
          sphinx-build -b html . ./docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs  # This must match the folder where your HTML was built
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4